# Generated by Django 4.2.23 on 2025-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('director', 'Director')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, '1st Sem'), (2, '2nd Sem'), (3, '3rd Sem'), (4, '4th Sem')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('AI/ML', 'AI/ML'), ('CC', 'CC'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ussn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year')], null=True),
        ),
    ]
